import { ChatIntent, intentKeywords, knowledge } from '../data/hydroponicsIndiaKnowledge';

export type ChatContext = { currentIntent: ChatIntent; userType?: 'farmer' | 'entrepreneur' | 'supplier' | 'buyer'; lastTopic?: ChatIntent; recentTopics: ChatIntent[] };
export type ChatReply = { text: string; intent: ChatIntent; suggestions: string[] };

export const normalizeInput = (input: string) => input.toLowerCase().replace(/[’']/g, "'").replace(/[^a-z0-9$₹\s']/g, ' ').replace(/\s+/g, ' ').trim();

export function detectIntent(input: string, context: ChatContext): ChatIntent {
  const text = normalizeInput(input);
  if (!text) return 'unknown';
  let best: ChatIntent = 'unknown'; let score = 0;
  Object.entries(intentKeywords).forEach(([intent, keywords]) => { const hits = keywords.reduce((count, keyword) => count + (text.includes(keyword) ? (keyword.includes(' ') ? 3 : 1) : 0), 0); if (hits > score) { best = intent as ChatIntent; score = hits; } });
  if (best === 'unknown' && /how much|kitna|cost|price|lagega/.test(text)) return context.lastTopic === 'equipment' || context.currentIntent === 'farmer' ? 'equipment' : 'business';
  if (best === 'unknown' && /what about|aur|iske baare|tell me more/.test(text)) return context.lastTopic || context.currentIntent;
  return best;
}

export function detectUserType(input: string): ChatContext['userType'] { const text = normalizeInput(input); if (text.includes('farmer') || text.includes('kisan')) return 'farmer'; if (text.includes('entrepreneur') || text.includes('business')) return 'entrepreneur'; if (text.includes('supplier') || text.includes('equipment maker')) return 'supplier'; if (text.includes('buyer') || text.includes('retailer')) return 'buyer'; return undefined; }

export function updateContext(context: ChatContext, input: string, intent: ChatIntent): ChatContext { const userType = detectUserType(input); return { ...context, currentIntent: intent, lastTopic: intent === 'greeting' || intent === 'thanks' ? context.lastTopic : intent, recentTopics: [intent, ...context.recentTopics.filter((topic) => topic !== intent)].slice(0, 5), ...(userType ? { userType } : {}) }; }

const suggestions: Record<ChatIntent, string[]> = { greeting: ['What is HydroponicsIndia?', 'How does hydroponic farming work?', "I'm a farmer"], thanks: ['What can you help me with?', 'Tell me about training'], identity: ['What is HydroponicsIndia?', 'How can you help farmers?'], whatIs: ['Who is it for?', 'How does the ecosystem work?', 'What services are included?'], hydroponics: ['How does it save water?', 'What crops can be grown?', 'How do I start?'], ecosystem: ['Tell me about farmers', 'What technology is included?', 'How does market access work?'], farmer: ['Hydroponics basics', 'Crop selection', 'Infrastructure', 'Market access'], training: ['Technician certification', 'Farmer training', 'Entrepreneur development'], technician: ['What training is available?', 'How does technical support work?'], equipment: ['Can I rent equipment?', 'What does installation include?', 'Tell me about sensors'], support: ['How do I become a technician?', 'Tell me about remote monitoring'], ai: ['Crop recommendations', 'Nutrient management', 'Disease alerts', 'Yield optimization'], finance: ['Can I get a loan?', 'Equipment rental', 'Lease-to-own'], market: ['How do I find buyers?', 'What is export readiness?', 'Tell me about traceability'], business: ['How much does it cost?', 'Tell me about cashflow', 'What is the business model?'], funding: ['How will the funds be used?', 'What is the business model?'], roadmap: ['Is it available nationwide?', 'What is proposed versus live?'], contact: ['I am a farmer', 'Tell me about joining'], unknown: ['What is hydroponics?', 'Tell me about training', 'How does finance work?'] };

export function getSuggestions(intent: ChatIntent) { return suggestions[intent]; }

export function getResponse(input: string, context: ChatContext): ChatReply { const intent = detectIntent(input, context); const text = normalizeInput(input); let response = knowledge[intent as keyof typeof knowledge]; if (intent === 'greeting') response = text.includes('namaste') ? 'Namaste! I’m the HydroponicsIndia Assistant. What would you like to explore?' : 'Hello! I’m the HydroponicsIndia Assistant. I can help you explore the hydroponics ecosystem, training, technology, finance and market access.'; if (intent === 'thanks') response = 'You’re welcome. I’m here whenever you want to explore the HydroponicsIndia ecosystem.'; if (intent === 'identity') response = 'I’m the HydroponicsIndia Assistant, a frontend conversational guide to hydroponic farming, the platform vision and its ecosystem. I do not connect to live farm, sensor, buyer or financing systems.'; if (intent === 'technician') response = knowledge.training + '\n\nThe ecosystem also envisions certified technicians and on-demand technical support, but I cannot confirm an active registry or issue a credential here.'; if (intent === 'finance' && /loan|loan kaise/.test(text)) response = knowledge.finance; if (intent === 'equipment' && /cost|price|kitna|lagega/.test(text)) response = knowledge.farmer; if (intent === 'ai' && /diagnos|disease|current nutrient|my crop/.test(text)) response += '\n\nI can explain the proposed capability, but I cannot diagnose your crop or provide live nutrient requirements through this website chatbot.'; if (intent === 'unknown') response = `I don't have verified HydroponicsIndia information about that yet. I can help with hydroponic farming, training, infrastructure, equipment, finance, AI guidance, technical support, market access and the platform ecosystem.`; return { text: response || knowledge.ecosystem, intent, suggestions: getSuggestions(intent) }; }